repos:
  - repo: local
    hooks:
      - id: go-test
        name: Run Go tests before commit
        entry: go test ./...
        language: system
        pass_filenames: false   # <-- this tells pre-commit NOT to pass file args
        types: [go]
